[USER_INPUT]
# Buttons
RED_BUTTON    = hm2_7i92.0.7i73.0.2.input-16
GREEN_BUTTON  = hm2_7i92.0.7i73.0.2.input-17
YELLOW_BUTTON = hm2_7i92.0.7i73.0.2.input-18
WHITE_BUTTON  = hm2_7i92.0.7i73.0.2.input-19
BLUE_BUTTON   = hm2_7i92.0.7i73.0.2.input-20

# Step Size
STEP_0_100 = hm2_7i92.0.7i73.0.2.input-00
STEP_0_010 = hm2_7i92.0.7i73.0.2.input-01
STEP_0_001 = hm2_7i92.0.7i73.0.2.input-02

# Axis Select
X_AXIS_SELECT = hm2_7i92.0.7i73.0.2.input-07
Y_AXIS_SELECT = hm2_7i92.0.7i73.0.2.input-03
Z_AXIS_SELECT = hm2_7i92.0.7i73.0.2.input-04
A_AXIS_SELECT = hm2_7i92.0.7i73.0.2.input-05
B_AXIS_SELECT = hm2_7i92.0.7i73.0.2.input-06

# Encoder Switch
LEFT_ENCODER_SW  = hm2_7i92.0.7i73.0.2.input-15
RIGHT_ENCODER_SW = hm2_7i92.0.7i73.0.2.input-14

# Encoders
MPG_ENCODER   = hm2_7i92.0.7i73.0.2.enc0
LEFT_ENCODER  = hm2_7i92.0.7i73.0.2.enc2
RIGHT_ENCODER = hm2_7i92.0.7i73.0.2.enc1

# Spindle
SPINDLE_UNLOCK = lcec.0.FIELD_INPUT.din-7

[USER_OUTPUT]
# LEDs
RED_BUTTON_LED    = hm2_7i92.0.7i73.0.2.output-10
GREEN_BUTTON_LED  = hm2_7i92.0.7i73.0.2.output-11
YELLOW_BUTTON_LED = hm2_7i92.0.7i73.0.2.output-12
WHITE_BUTTON_LED  = hm2_7i92.0.7i73.0.2.output-13
BLUE_BUTTON_LED   = hm2_7i92.0.7i73.0.2.output-14
